### ISSUE TITLE
compose.bcc() not working

### ISSUE THREAD

**Issue by markon1** [KartikTalwar/gmail.js#712]
I'm trying to read `bcc` from compose, but it gives this error:

    ```
TypeError: Cannot read properties of undefined (reading 'focus')
    at _0x5c1229.<computed>.<computed>.<computed> [as trigger_address] (gmailJsLoader.js:1:322215)
    at _0x5c1229.<computed>.<computed>.bcc (gmailJsLoader.js:1:325624)
```

**Comment by josteink** [comment]
This may be related to a change introduced in 1.0.15. 

Can you take a look @huksley ?

**Comment by markon1** [comment]
Any news? Some hotfix maybe? My app is broken with this..

**Comment by josteink** [comment]
Have you tried latest version from Git master?

I recently merged a PR which may have helped with this issue: https://github.com/KartikTalwar/gmail.js/pull/714

**Comment by josteink** [comment]
If that works for you, I can push a new release to npm.

**Comment by markon1** [comment]
thanks @josteink but with this version when I try adding bcc, first bcc I add is fine, but it's not "clicked" (confirmed) automatically, so if I try adding next bcc, it doesn't work, it expects me to confirm first bcc I added, so it look like this if I click on bcc button in gmail:
![image](https://user-images.githubusercontent.com/11547451/183255741-e6f51982-f281-4e98-a7ac-92aed1c9cd1f.png)

**Comment by josteink** [comment]
Could you look at this, @onestep ? It's "your code" after all :)

**Comment by markon1** [comment]
Any updates on this? @onestep

**Comment by onestep** [comment]
Hello @josteink, we've worked this around with custom click triggers in own code. 🙂 Not sure if it is ready for general usage, as it's quite hacky (`setTimeout()` usage, mutation observers and so on). And i'm not sure if it covers _bcc_ as well - I remember that we've fixed it for _to_.
If I will have time, I'll try to include it in some clean way in gmail.js.

**Comment by onestep** [comment]
Looking on our code, we've changed this:
```e.to(params.to);```
To this:
```e.to(params.to)[0].dispatchEvent(new KeyboardEvent('keydown', { keyCode: 13, which: 13 }));```
Hope this helps.
