### ISSUE TITLE
GmailJS library (1.1.14) is failing to load (with error in console)

### ISSUE THREAD

**Issue by shashikiran-im** [KartikTalwar/gmail.js#787]
Hi GmailJS Team,
					
From two / three days I observed Gmail JS is failing to load in Gmail page and it is throwing error as below,
Also I tried boilerplate project with latest Gmail JS version 1.1.14 and observed same issue.

**Error in console:**					
Uncaught TypeError: Failed to set the 'innerHTML' property on 'Element': This document requires 'TrustedHTML' assignment.
					    at jquery.js:4665:6
					    at jquery.js:4673:1
					    at jquery.js:25:4
					    at node_modules/jquery/dist/jquery.js (jquery.js:37:1)
					    at __require (gmailJsLoader.js:5:52)
					    at gmailJsLoader.js:14:16
					    at gmailJsLoader.js:18:67

Please let me know if anyone facing similar issue.
Kindly request to let me know if anyone knows root cause of the issue so that I will give a try to address / if anyone is addressed the issue.
					
Thanks in Advance,
Shashikiran

**Comment by josteink** [comment]
See this thread for details:

https://github.com/KartikTalwar/gmail.js/issues/779

**Comment by josteink** [comment]
See the updated boilerplate repo for how to cirumvent this:

https://github.com/josteink/gmailjs-node-boilerplate/blob/master/src/gmailJsLoader.js
